// Generated by scripts/gen-kimya.mjs from data/dim_kimya_movzular.json. Do not edit by hand.
const NAMES: Record<string, string> = {
  "K01": "Kimyanın əsas anlayışları",
  "K02": "Mol. Molyar kütlə və molyar həcm",
  "K03": "Reaksiya tənliyi üzrə hesablamalar",
  "K04": "Atomun quruluşu",
  "K05": "Dövri qanun və dövri sistem",
  "K06": "Kimyəvi rabitə",
  "K07": "Hibridləşmə və molekulun fəza quruluşu",
  "K08": "Kristal qəfəslər və aqreqat hallar",
  "K09": "Reaksiyaların təsnifatı. Termokimya",
  "K10": "Kimyəvi reaksiyanın sürəti",
  "K11": "Kimyəvi tarazlıq",
  "K12": "Məhlullar və qatılıq",
  "K13": "Elektrolitik dissosiasiya və ion mübadiləsi",
  "K14": "Duzların hidrolizi",
  "K15": "Oksidləşmə-reduksiya reaksiyaları",
  "K16": "Elektroliz. Gərginlik sırası",
  "K17": "Qeyri-üzvi birləşmələrin sinifləri",
  "K18": "Hidrogen və halogenlər",
  "K19": "Oksigen və kükürd",
  "K20": "Azot və fosfor",
  "K21": "Karbon və silisium (qeyri-üzvi)",
  "K22": "Metalların ümumi xassələri",
  "K23": "Qələvi, qələvi-torpaq metallar, alüminium, dəmir",
  "K24": "Üzvi kimyanın əsasları",
  "K25": "Alkanlar və tsikloalkanlar",
  "K26": "Alkenlər, alkadienlər, alkinlər",
  "K27": "Arenlər. Karbohidrogenlərin təbii mənbələri",
  "K28": "Spirtlər və fenollar",
  "K29": "Aldehidlər, ketonlar, karbon turşuları",
  "K30": "Mürəkkəb efirlər və yağlar",
  "K31": "Karbohidratlar",
  "K32": "Azotlu üzvi birləşmələr",
  "K33": "Polimerlər"
}

// "K03" -> "K03 — <name>"; math topics (plain names) and UNSURE pass through unchanged.
export const topicLabel = (topic: string) => (NAMES[topic] ? `${topic} — ${NAMES[topic]}` : topic)

// Name only, for student-facing text.
export const topicName = (topic: string) => NAMES[topic] ?? topic
