-- Generated by scripts/gen-kimya.mjs from data/miq_kimya_suallar_TETBIQ_UCUN.json. Safe to re-run.
-- Topics and reasons are intentionally null: they come only from the live AI call.
insert into groups (id, name, subject) values
  ('44444444-4444-4444-8444-444444444444', 'Kimya qrupu', 'chemistry')
on conflict (id) do nothing;

insert into quizzes (id, group_id, title, status) values
  ('55555555-5555-4555-8555-555555555555', '44444444-4444-4444-8444-444444444444', $kq$MİQ Günün sualları — 03.09.2025$kq$, 'live')
on conflict (id) do nothing;

insert into questions (id, quiz_id, position, text, topic, options, correct_label, misconceptions) values
  ('66666666-6666-4666-8666-000000000001', '55555555-5555-4555-8555-555555555555', 1, $kq$2XY2(q) → X2(q) + 2Y2(q) reaksiyasında 1,2 mol XY2 qazından 25% çıxımla X2 və Y2 qazları əmələ gəlir.
Hansı ifadələr doğrudur?
I. 0,6 mol Y2 qazı əmələ gəlir.
II. Molekul sayı 1,5 dəfə artır
III. 0,9 mol XY2 qazı artıq qalır.$kq$, null, $kq$[{"label":"A","text":"yalnız I"},{"label":"B","text":"yalnız II"},{"label":"C","text":"yalnız III"},{"label":"D","text":"I, III"},{"label":"E","text":"I, II, III"}]$kq$::jsonb, 'C', null),
  ('66666666-6666-4666-8666-000000000002', '55555555-5555-4555-8555-555555555555', 2, $kq$25 °C-də 0,05 mol HCl olan 500 ml məhlulun pH dəyərini hesablayın.$kq$, null, $kq$[{"label":"A","text":"1"},{"label":"B","text":"2"},{"label":"C","text":"3"},{"label":"D","text":"4"},{"label":"E","text":"5"}]$kq$::jsonb, 'A', null),
  ('66666666-6666-4666-8666-000000000003', '55555555-5555-4555-8555-555555555555', 3, $kq$Eyni həcmdə qatılığı 0,4 M olan MgCl2 məhlulu ilə qatılığı 0,6 M olan AlCl3 məhlulu qarışdırıldıqda alınan məhlulda Cl- ionun qatılığını müəyyən edin.$kq$, null, $kq$[{"label":"A","text":"1,1"},{"label":"B","text":"1,2"},{"label":"C","text":"1,3"},{"label":"D","text":"1,4"},{"label":"E","text":"1,5"}]$kq$::jsonb, 'C', null),
  ('66666666-6666-4666-8666-000000000004', '55555555-5555-4555-8555-555555555555', 4, $kq$Rabitə | Rabitə enerjisi, kC/mol
C=C | 620
C-H | 414
C=O | 745
O-H | 460
Cədvələ əsasən C2H4-ün yanma reaksiyasında O=O rabitə enerjisini (kC/mol) hesablayın.
C2H4-ün yanma istiliyi 1050 kC/mol-dur.$kq$, null, $kq$[{"label":"A","text":"372"},{"label":"B","text":"424"},{"label":"C","text":"448"},{"label":"D","text":"498"},{"label":"E","text":"526"}]$kq$::jsonb, 'D', null),
  ('66666666-6666-4666-8666-000000000005', '55555555-5555-4555-8555-555555555555', 5, $kq$CaH2-in az miqdarda su ilə reaksiyası zamanı alınan bərk qalıqda oksigenin kütlə payı 20% olarsa, bərk nümunənin kütləsi neçə faiz artmışdır?$kq$, null, $kq$[{"label":"A","text":"15"},{"label":"B","text":"20"},{"label":"C","text":"25"},{"label":"D","text":"28"},{"label":"E","text":"36"}]$kq$::jsonb, 'C', null)
on conflict (id) do nothing;
