// Generates, from the files in data/:
//  - supabase/functions/analyze-quiz/topics_kimya.ts   (id, ad, ehate only; acar_sozler never leaves data/)
//  - src/lib/topicNames.ts                             (id -> ad, for display)
//  - supabase/seed_kimya.sql                           (Kimya qrupu + quiz MIQ_2025-09-03 only)
// MIQ_2024-10-03 is the blind-test quiz and is never seeded.
import fs from 'node:fs'

const read = (p) => JSON.parse(fs.readFileSync(p, 'utf8'))
const dim = read('data/dim_kimya_movzular.json')
const quizzes = read('data/miq_kimya_suallar_TETBIQ_UCUN.json').quizzes

const topics = dim.movzular.map(({ id, ad, ehate }) => ({ id, ad, ehate }))
if (topics.length !== 33) throw new Error(`expected 33 topics, got ${topics.length}`)

fs.writeFileSync(
  'supabase/functions/analyze-quiz/topics_kimya.ts',
  `// Generated by scripts/gen-kimya.mjs from data/dim_kimya_movzular.json. Do not edit by hand.
// Only id, ad and ehate go to the prompt; the keyword lists (acar_sozler) are not included.
export const KIMYA_TOPICS: { id: string; ad: string; ehate: string }[] = ${JSON.stringify(topics, null, 2)}
`,
)

fs.writeFileSync(
  'src/lib/topicNames.ts',
  `// Generated by scripts/gen-kimya.mjs from data/dim_kimya_movzular.json. Do not edit by hand.
const NAMES: Record<string, string> = ${JSON.stringify(Object.fromEntries(topics.map((t) => [t.id, t.ad])), null, 2)}

// "K03" -> "K03 — <name>"; math topics (plain names) and UNSURE pass through unchanged.
export const topicLabel = (topic: string) => (NAMES[topic] ? \`\${topic} — \${NAMES[topic]}\` : topic)

// Name only, for student-facing text.
export const topicName = (topic: string) => NAMES[topic] ?? topic
`,
)

const quiz = quizzes.find((q) => q.quiz_id === 'MIQ_2025-09-03')
const GROUP = '44444444-4444-4444-8444-444444444444'
const QUIZ = '55555555-5555-4555-8555-555555555555'
const dq = (s) => `$kq$${s}$kq$`
const rows = quiz.questions.map((q, i) => {
  const options = Object.entries(q.options).map(([label, text]) => ({ label, text }))
  const id = `66666666-6666-4666-8666-${String(i + 1).padStart(12, '0')}`
  return `  ('${id}', '${QUIZ}', ${i + 1}, ${dq(q.question_text)}, null, ${dq(JSON.stringify(options))}::jsonb, '${q.correct}', null)`
})

fs.writeFileSync(
  'supabase/seed_kimya.sql',
  `-- Generated by scripts/gen-kimya.mjs from data/miq_kimya_suallar_TETBIQ_UCUN.json. Safe to re-run.
-- Topics and reasons are intentionally null: they come only from the live AI call.
insert into groups (id, name, subject) values
  ('${GROUP}', 'Kimya qrupu', 'chemistry')
on conflict (id) do nothing;

insert into quizzes (id, group_id, title, status) values
  ('${QUIZ}', '${GROUP}', ${dq('MİQ Günün sualları — 03.09.2025')}, 'live')
on conflict (id) do nothing;

insert into questions (id, quiz_id, position, text, topic, options, correct_label, misconceptions) values
${rows.join(',\n')}
on conflict (id) do nothing;
`,
)
console.log('generated', topics.length, 'topics and', quiz.questions.length, 'questions')
