// Generated by scripts/gen-kimya.mjs from data/dim_kimya_movzular.json. Do not edit by hand.
// Only id, ad and ehate go to the prompt; the keyword lists (acar_sozler) are not included.
export const KIMYA_TOPICS: { id: string; ad: string; ehate: string }[] = [
  {
    "id": "K01",
    "ad": "Kimyanın əsas anlayışları",
    "ehate": "maddə, element, qarışıq, fiziki və kimyəvi hadisələr, kimyəvi formul, valentlik"
  },
  {
    "id": "K02",
    "ad": "Mol. Molyar kütlə və molyar həcm",
    "ehate": "mol, Avoqadro ədədi, molyar kütlə, normal şəraitdə molyar həcm, elementin kütlə payı, formulun tapılması, qazların nisbi sıxlığı"
  },
  {
    "id": "K03",
    "ad": "Reaksiya tənliyi üzrə hesablamalar",
    "ehate": "stexiometriya, artıq və çatışmayan maddə, praktiki çıxım, qarışığın tərkibi"
  },
  {
    "id": "K04",
    "ad": "Atomun quruluşu",
    "ehate": "proton, neytron, elektron, izotoplar, elektron konfiqurasiyası, orbitallar, kvant ədədləri"
  },
  {
    "id": "K05",
    "ad": "Dövri qanun və dövri sistem",
    "ehate": "dövr və qruplar, elektromənfilik, atom radiusu, ionlaşma enerjisi, xassələrin dəyişməsi"
  },
  {
    "id": "K06",
    "ad": "Kimyəvi rabitə",
    "ehate": "kovalent (polyar, qeyri-polyar), ion, metal, hidrogen rabitəsi, donor-akseptor, σ və π rabitələr, rabitə enerjisi və uzunluğu"
  },
  {
    "id": "K07",
    "ad": "Hibridləşmə və molekulun fəza quruluşu",
    "ehate": "sp, sp2, sp3 hibridləşmə, valent bucağı, molekulun forması"
  },
  {
    "id": "K08",
    "ad": "Kristal qəfəslər və aqreqat hallar",
    "ehate": "ion, atom, molekul və metal kristal qəfəsləri"
  },
  {
    "id": "K09",
    "ad": "Reaksiyaların təsnifatı. Termokimya",
    "ehate": "birləşmə, parçalanma, əvəzetmə, mübadilə reaksiyaları; ekzo- və endotermik reaksiyalar, termokimyəvi tənlik, Hess qanunu"
  },
  {
    "id": "K10",
    "ad": "Kimyəvi reaksiyanın sürəti",
    "ehate": "sürətə təsir edən amillər, katalizator, Vant-Hoff qaydası, aktivləşmə enerjisi"
  },
  {
    "id": "K11",
    "ad": "Kimyəvi tarazlıq",
    "ehate": "Le Şatelye prinsipi, tarazlıq sabiti, tarazlığın yerdəyişməsi"
  },
  {
    "id": "K12",
    "ad": "Məhlullar və qatılıq",
    "ehate": "məhlulda kütlə payı, molyar qatılıq, həllolma, kristalhidratlar, durulaşdırma və qarışdırma"
  },
  {
    "id": "K13",
    "ad": "Elektrolitik dissosiasiya və ion mübadiləsi",
    "ehate": "elektrolitlər, dissosiasiya dərəcəsi, ion tənlikləri, mühit, pH, indikatorlar"
  },
  {
    "id": "K14",
    "ad": "Duzların hidrolizi",
    "ehate": "hidroliz tipləri, məhlulun mühiti"
  },
  {
    "id": "K15",
    "ad": "Oksidləşmə-reduksiya reaksiyaları",
    "ehate": "oksidləşmə dərəcəsi, oksidləşdirici və reduksiyaedici, elektron balansı"
  },
  {
    "id": "K16",
    "ad": "Elektroliz. Gərginlik sırası",
    "ehate": "ərintilərin və məhlulların elektrolizi, katod və anod prosesləri, metalların gərginlik sırası"
  },
  {
    "id": "K17",
    "ad": "Qeyri-üzvi birləşmələrin sinifləri",
    "ehate": "oksidlər, əsaslar, turşular, duzlar, amfoterlik, genetik əlaqə"
  },
  {
    "id": "K18",
    "ad": "Hidrogen və halogenlər",
    "ehate": "hidrogen, halogenlər və onların birləşmələri"
  },
  {
    "id": "K19",
    "ad": "Oksigen və kükürd",
    "ehate": "oksigen, ozon, kükürd və birləşmələri, sulfat turşusu"
  },
  {
    "id": "K20",
    "ad": "Azot və fosfor",
    "ehate": "azot, ammonyak, nitrat turşusu, fosfor və birləşmələri, gübrələr"
  },
  {
    "id": "K21",
    "ad": "Karbon və silisium (qeyri-üzvi)",
    "ehate": "karbon oksidləri, karbonatlar, silisium və silikatlar"
  },
  {
    "id": "K22",
    "ad": "Metalların ümumi xassələri",
    "ehate": "metalların alınması, korroziya, ərintilər"
  },
  {
    "id": "K23",
    "ad": "Qələvi, qələvi-torpaq metallar, alüminium, dəmir",
    "ehate": "IA, IIA metallar, alüminium, dəmir və onların birləşmələri, suyun codluğu"
  },
  {
    "id": "K24",
    "ad": "Üzvi kimyanın əsasları",
    "ehate": "quruluş nəzəriyyəsi, izomeriya, homoloji sıra, nomenklatura, funksional qruplar"
  },
  {
    "id": "K25",
    "ad": "Alkanlar və tsikloalkanlar",
    "ehate": "doymuş karbohidrogenlər, xassələri və alınması"
  },
  {
    "id": "K26",
    "ad": "Alkenlər, alkadienlər, alkinlər",
    "ehate": "doymamış karbohidrogenlər, kauçuk"
  },
  {
    "id": "K27",
    "ad": "Arenlər. Karbohidrogenlərin təbii mənbələri",
    "ehate": "benzol və homoloqları, neft, təbii qaz, krekinq"
  },
  {
    "id": "K28",
    "ad": "Spirtlər və fenollar",
    "ehate": "biratomlu və çoxatomlu spirtlər, fenol"
  },
  {
    "id": "K29",
    "ad": "Aldehidlər, ketonlar, karbon turşuları",
    "ehate": "karbonil və karboksil birləşmələri"
  },
  {
    "id": "K30",
    "ad": "Mürəkkəb efirlər və yağlar",
    "ehate": "efirləşmə, yağlar, sabun"
  },
  {
    "id": "K31",
    "ad": "Karbohidratlar",
    "ehate": "qlükoza, fruktoza, saxaroza, nişasta, sellüloza"
  },
  {
    "id": "K32",
    "ad": "Azotlu üzvi birləşmələr",
    "ehate": "aminlər, anilin, aminturşular, zülallar"
  },
  {
    "id": "K33",
    "ad": "Polimerlər",
    "ehate": "polimerləşmə, polikondensləşmə, plastik kütlələr, liflər"
  }
]
